language: python
python:
  - "2.7"
before_install:
  - "sudo add-apt-repository -y ppa:ubuntugis/ppa"
  - "sudo apt-get update -qq"
  - "sudo apt-get install -y libgdal1h gdal-bin libgdal-dev"
install:
  - "./.travis-install-platter.sh"
  - "pip install -r requirements-dev.txt"
  - "pip install -e .[test]"
script: 
  - "py.test"
  - "coverage run --source=rio_mbtiles -m py.test"
after_success:
  - "coveralls"
