language: python
python:
  - "2.7"
  - "3.4"
addons:
  apt:
    sources:
    - lucid
addons:
  apt:
    packages:
    - libgdal1h
    - gdal-bin
    - libgdal-dev
install:
  - 'pip install --install-option="--no-cython-compile" cython==0.21.2'
  - "pip install -r requirements-dev.txt"
  - "pip install coveralls"
  - "pip install -e .[test]"
script: 
  - py.test
  - "coverage run --source=rio_mbtiles -m py.test"
after_success:
  - coveralls
sudo: false
cache:
  directories:
    - $HOME/virtualenv/python2.7.9/lib/python2.7/site-packages
    - $HOME/virtualenv/python3.4.3/lib/python2.7/site-packages
