language: python
python:
  - "2.7"
  - "3.4"
before_install:
  - "sudo add-apt-repository -y ppa:ubuntugis/ppa"
  - "sudo apt-get update -qq"
  - "sudo apt-get install -y libgdal1h gdal-bin libgdal-dev"
install:
  - "wget https://s3.amazonaws.com/mapbox/rasterio/rio-0.23.0.tar.gz -o /home/travis/virtualenv/rio-0.23.0.tar.gz"
  - "cd /home/travis/virtualenv && tar xzf rio-0.23.0.tar.gz"
  - "pip install -r requirements-dev.txt"
  - "pip install coveralls"
  - "pip install -e .[test]"
script: 
  - py.test
  - "coverage run --source=rio_mbtiles -m py.test"
after_success:
  - coveralls
