language: python
python:
  - "2.7"
before_install:
  - "sudo add-apt-repository -y ppa:ubuntugis/ppa"
  - "sudo apt-get update -qq"
  - "sudo apt-get install -y libgdal1h gdal-bin libgdal-dev"
install:
  - "./.travis-install-platter.sh"
  - "pip install coveralls"
  - "pip install -e .[test]"
script:
  - "py.test --cov rio_mbtiles --cov-report term-missing"
after_success:
  - "coveralls"
