language: python
python:
  - "2.7"
  - "3.4"
before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y libgdal1h gdal-bin libgdal-dev
install:
  - pip install --install-option="--no-cython-compile" cython
  - "pip install coveralls"
  - "pip install -e .[test]"
script: 
  - py.test
  - coverage run --source=rio_mbtiles -m py.test
after_success:
  - coveralls
