language: python
python:
  - "2.7"
cache:
  directories:
    - $HOME/.pip-cache/
    - /home/travis/virtualenv/python2.7
before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y libgdal1h gdal-bin libgdal-dev
install:
  - ./.travis-install-platter.sh
  - pip install coveralls --cache-dir $HOME/.pip-cache
  - pip install -e .[test] --cache-dir $HOME/.pip-cache
script:
  - py.test --cov mbtiles --cov-report term-missing
after_success:
  - coveralls
