language: python
sudo: false
python:
  - "2.7"
  - "3.4"
cache:
  directories:
    - $HOME/.pip-cache/
    - $HOME/wheelhouse
before_install:
  - add-apt-repository -y ppa:ubuntugis/ppa
  - apt-get update -qq
  - apt-get install -y libgdal1h gdal-bin
  - curl -L https://github.com/mapbox/rasterio/releases/download/release-test-4/rasterio-travis-wheels-$TRAVIS_PYTHON_VERSION.tar.gz > /tmp/wheelhouse.tar.gz
  - tar -xzvf /tmp/wheelhouse.tar.gz -C $HOME
install:
  - pip install --use-wheel --find-links=$HOME/wheelhouse -e .[test] --cache-dir $HOME/.pip-cache
script:
  - py.test --cov mbtiles --cov-report term-missing
after_success:
  - coveralls
